### ISSUE TITLE
help      can not train

### ISSUE THREAD

**Issue by clin-fu** [scenenn/pointwise#14]
hello, i am sorry to trouble you .  when i use your code ,i met some problem.
(tensorflow1.9.0  cuda9.0  python3.5) 
command$ python train_modelnet40_acsd.py

  error:   Traceback (most recent call last):
  File "train_modelnet40_acsd.py", line 179, in <module>
    train(args)
  File "train_modelnet40_acsd.py", line 33, in train
    model = importlib.import_module(model_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/f/f1/step2 point wise/pointwise-master/pointcnn2_acsd.py", line 10, in <module>
    conv3p_module = tf.load_op_library(BASE_DIR + '/tf_ops/conv3p/tf_conv3p.so')
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/f/f1/step2 point wise/pointwise-master/tf_ops/conv3p/tf_conv3p.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringB5cxx11Ev

**Comment by songuke** [comment]
Could you see the solution in this issue: https://github.com/scenenn/pointwise/issues/7 

It could be related to some ABI flag in gcc. Thanks.

**Comment by clin-fu** [comment]
thanks ，i made a mistake yesterday. now it is working .




------------------ 原始邮件 ------------------
发件人: "Binh-Son Hua"<notifications@github.com>; 
发送时间: 2019年7月1日(星期一) 晚上11:37
收件人: "scenenn/pointwise"<pointwise@noreply.github.com>; 
抄送: "妞妞打蛋蛋"<571246870@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [scenenn/pointwise] help      can not train (#14)




Could you see the solution in this issue: #7
 
It could be related to some ABI flag in gcc. Thanks.
