### ISSUE TITLE
tensorflow error

### ISSUE THREAD

**Issue by rnunziata** [scenenn/pointwise#6]
Getting tensorflow error:
I am running ubuntu 16.04...cuda-9.2 tensorflow-gpu=1.10

```
python3 eval_modelnet40_acsd.py
Using model  pointcnn2_acsd
Categories:  40
Sort cloud:  True
Using device /cpu:0
2018-08-25 16:51:31.214054: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-08-25 16:51:31.215224: E tensorflow/stream_executor/cuda/cuda_driver.cc:397] failed call to cuInit: CUDA_ERROR_UNKNOWN
2018-08-25 16:51:31.215266: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] retrieving CUDA diagnostic information for host: rjn-Oryx-Pro
2018-08-25 16:51:31.215291: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:170] hostname: rjn-Oryx-Pro
2018-08-25 16:51:31.215325: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:194] libcuda reported version is: 396.44.0
2018-08-25 16:51:31.215393: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:198] kernel reported version is: 396.44.0
2018-08-25 16:51:31.215399: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:305] kernel version seems to match DSO: 396.44.0
Traceback (most recent call last):
  File "eval_modelnet40_acsd.py", line 115, in <module>
    eval(args)
  File "eval_modelnet40_acsd.py", line 60, in eval
    batch_prediction_placeholder = network.model(batch_points_placeholder, batch_input_placeholder, is_training=False)
  File "/home/rjn/projects/3D-Classifiction/pointwise/pointcnn2_acsd.py", line 51, in model
    conv1 = conv3p(points_tensor, input_tensor, filter1_tensor, stride, voxel_size);
  File "/home/rjn/projects/3D-Classifiction/pointwise/pointcnn2_acsd.py", line 13, in conv3p
    return conv3p_module.conv3p(points_tensor, input_tensor, kernel_tensor, stride, voxel_size);
  File "<string>", line 52, in conv3p
  File "/home/rjn/.local/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 394, in _apply_op_helper
    with g.as_default(), ops.name_scope(name) as scope:
  File "/home/rjn/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 5775, in __enter__
    return self._name_scope.__enter__()
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/rjn/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3837, in name_scope
    if name:
  File "/home/rjn/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 638, in __bool__
    raise TypeError("Using a `tf.Tensor` as a Python `bool` is not allowed. "
TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use TensorFlow ops such as tf.cond to execute subgraphs conditioned on the value of a tensor.

```

**Comment by songuke** [comment]
Could you try if this solution works: https://github.com/scenenn/pointwise/issues/5

**Comment by rnunziata** [comment]
yes that was it....sorry...I missed that in the README....thank you .
