### ISSUE TITLE
undefined symbol

### ISSUE THREAD

**Issue by yurunsheng1** [scenenn/pointwise#7]
Hi,
I meet a problem and really need your help.

When I was running train_modelnet40_acsd.py:

**/home/sdd/anaconda3/bin/python /home/sdd/Documents/code/pointwise-master/train_modelnet40_acsd.py**

I meet a problem:
 `
/home/sdd/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`. 
 ` 
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/home/sdd/Documents/code/pointwise-master/train_modelnet40_acsd.py", line 179, in <module>
    train(args)
  File "/home/sdd/Documents/code/pointwise-master/train_modelnet40_acsd.py", line 33, in train
    model = importlib.import_module(model_name)
  File "/home/sdd/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/sdd/Documents/code/pointwise-master/pointcnn2_acsd.py", line 10, in <module>
    conv3p_module = tf.load_op_library(BASE_DIR + '/tf_ops/conv3p/tf_conv3p.so')
  File "/home/sdd/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/sdd/Documents/code/pointwise-master/tf_ops/conv3p/tf_conv3p.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringB5cxx11Ev

Process finished with exit code 1 

**May I ask you how to solve this problem? Thank you so much!**

**Comment by clintgt** [comment]
I have the same issue as well. I have compiled with "-a" flag for atrous conv. Which version of python 3.x is used?

**Comment by songuke** [comment]
I used Tensorflow 1.9 and Python 3.6.5. Which version of Tensorflow are you using?

**Comment by clintgt** [comment]
Alright, I am also using the same setting (TF 1.9) as you. Let me look into it and report back.

**Comment by clintgt** [comment]
This is the error " undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringB5**cxx11**Ev". I have gcc 5+, but TF from conda env (maybe other TF from other envs) are compiled with gcc < 5. So, comment out this line as said in the .sh script https://github.com/scenenn/pointwise/blob/master/tf_ops/conv3p/tf_conv3p_compile.sh#L29
